# Pipeline to deploy a preview of the site to Firebase Hosting on pull request

name: Deploy preview to Firebase Hosting on pull request
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: CI
        run: npm ci
      - name: Build
        run: npm run build-prod
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GAMES_C0672 }}
          projectId: games-c0672
